name: "Jarvis Infrastructure Deploy"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**' # Só roda se mexer na pasta do servidor
  workflow_dispatch: # Permite rodar manualmente clicando em um botão

env:
  # Injeta as credenciais para o Backend S3 funcionar (Crucial)
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server # Garante que rode na pasta certa

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        # Gera o plano e salva em arquivo para garantir consistência
        run: terraform plan -out=tfplan -input=false
        env:
          # Mapeia as variáveis do main.tf para os Secrets do GitHub
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_n8n_pass: ${{ secrets.N8N_PASS }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_admin_setup_key: ${{ secrets.ADMIN_SETUP_KEY }}
          TF_VAR_my_ip: ${{ secrets.MY_IP }}
          TF_VAR_ssh_key_name: "bruno-terraform-deployer" # Nome fixo da chave na AWS

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan