name: Deploy Jarvis Full Stack

on:
  push:
    branches: [ main ]

jobs:
  # --- JOB 1: BACKEND E INFRAESTRUTURA ---
  terraform-backend:
    runs-on: ubuntu-latest
    env:
      TF_VAR_admin_setup_key: ${{ secrets.ADMIN_SETUP_KEY }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - name: Quem sou eu na AWS?
        run: aws sts get-caller-identity
        
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Raio-X do Diretorio
        run: |
          echo "Verificando localizacao da pasta backend:"
          ls -R | grep -i "Jarvis_Server_backend" || echo "Pasta NAO encontrada no servidor"
          echo "Estrutura completa observada pelo robo:"
          ls -F

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./Jarvis_Server_backend/jarvis-serverless
        run: terraform init

      - name: Terraform Apply
        working-directory: ./Jarvis_Server_backend/jarvis-serverless
        run: terraform apply -auto-approve

  # --- JOB 2: FRONTEND (INTERFACE) ---
  build-and-deploy-ui:
    needs: terraform-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build
        env:
          VITE_APP_TITLE: "Jarvis 2.0"
          VITE_API_BASE_URL: "https://ucwealuc67.execute-api.us-east-1.amazonaws.com"

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'jarvis-user-interface'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist/public'
